version: '3.8'

services:
  alpine-python:
    image: alpine:latest
    command: tail -f /dev/null
    ports:
      - "5001:5001"  # Expose port 5001
    volumes:
      - chair_sit_consumer:/data  # Use named volume for persistent storage
    tty: true  # Keep the container running
    container_name: sit-stats-api-container
    environment:
      - TZ=America/Detroit  # Set timezone to Detroit, Michigan
    networks:
      - alpine-net
    entrypoint: |
      /bin/sh -c "
      apk add --no-cache openjdk11-jre-headless python3 py3-pip git;
      if [ ! -d /data/sit-stats-api ]; then
        git clone -b v1.1 --single-branch https://github.com/DevinMB/sit-stats-api.git /data/sit-stats-api;
      fi
      java -jar /data/sit-stats-api/sit.stats-0.0.1-SNAPSHOT.jar;
      "

networks:
  alpine-net:
    driver: bridge

volumes:
  chair_sit_consumer:  # Define the named volume
